version: '3'
services:
  app:
    container_name: expresso
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_URL= mongodb://john:doe@localhost:27017/dmongo'
      - PORT= 3000
    env_file:
      - my.env
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: dmongo
    volumes:
      - ./data:/data/db
    environment:
      spring.data.mongodb.database: dmongo
    ports:
      - "27017:27017"
