version: '3'
services:
  express:
    image: node:3.1-alpine
    container_name: expresso
    ports:
      - "3000:3000"
    volumes:
      - . :/test
    environment:
      - DB_URL= mongodb://john:doe@localhost:27017/dmongo'
      - PORT= 3000
    env_file:
      - my.env
    links:
      - mongodb
    command: npm start

  mongodb:
    image: mongo:latest
    container_name: dmongo
    environment:
      spring.data.mongodb.database: dmongo
    ports:
      - "27017:27017"
